<?php

require_once dirname(__FILE__) . '/../../pages/AdminMain.php';

/**
 * Test class for AdminMain.
 * Generated by PHPUnit on 2012-04-02 at 08:49:33.
 */
class AdminMainTest extends PHPUnit_Framework_TestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    public function testConstructorReturnsString() {
        ob_start();
        new AdminMain();
        
        $this->assertInternalType('string', ob_get_clean());
    }
    
}

?>
