<?php

require_once dirname(__FILE__) . '/../../class/Icon.php';

/**
 * Test class for Icon.
 * Generated by PHPUnit on 2012-03-29 at 10:21:22.
 */
class IconTest extends PHPUnit_Framework_TestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testPositionOffsetIsCorrectlySetPerImage() {
        $iconSize = 32;
        
        $iconNames = Icon::$AVAILABLE_ICONS;
        
        foreach ($iconNames as $key => $iconName) {
            $icon = new Icon($iconName, $iconSize);
            $this->assertEquals(-bcmul($iconSize, $key), $icon->getNegatedLeftOffset(), 'Failed at icon ' . $key . ' (' . $iconName . ')');
        }
    }
    
    public function testFalseIconNameReturnsMinusOne() {
        $icon = new Icon('falseName', 32);
        $this->assertEquals(-1, $icon->getNegatedLeftOffset());
    }
    
    public function testGetMarkup() {
        $iconSize = 32;
        $icon = new Icon('twitter', $iconSize);
        $this->assertEquals('<div style="width:'.$iconSize.'px;height:'.$iconSize.'px;background-image:url(../wp-content/plugins/multiplesocialmediaicons/icons/socialMediaBookmarkIconsSpriteCompressed.png);background-position:'.$icon->getNegatedLeftOffset().'px 0;">'.
                            '<a style="display:block;width:'.$iconSize.'px;height:'.$iconSize.'px;" href="#" title="Follow me on twitter" target="_blank"></a></div>', $icon->getMarkup());
    }
    
    public function testGetMarkupWithCustomValues() {
        $iconSize = 64;
        $customLink = 'http://www.dixpix.de';
        $customTitle = 'This is my custom title';
        
        $icon = new Icon('stumbleupon', $iconSize);
        $icon->setCustomIconLink($customLink);
        $icon->setCustomIconTitle($customTitle);
        $this->assertEquals('<div style="width:'.$iconSize.'px;height:'.$iconSize.'px;background-image:url(../wp-content/plugins/multiplesocialmediaicons/icons/socialMediaBookmarkIconsSpriteCompressed.png);background-position:'.$icon->getNegatedLeftOffset().'px 0;">'.
                            '<a style="display:block;width:'.$iconSize.'px;height:'.$iconSize.'px;" href="'.$customLink.'" title="'.$customTitle.'" target="_blank"></a></div>', $icon->getMarkup());
    }
}