<?php

require_once dirname(__FILE__) . '/../../../class/IconSet.php';

/**
 * Test class for IconSet.
 * Generated by PHPUnit on 2012-03-29 at 10:21:22.
 */
class IconSetTest extends PHPUnit_Framework_TestCase {

    /**
     * @var IconSet
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new IconSet;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
