<?php

require_once dirname(__FILE__) . '/../../../class/IconSet.php';
require_once dirname(__FILE__) . '/../../../class/Icon.php';
/**
 * Test class for IconSet.
 * Generated by PHPUnit on 2012-03-29 at 10:21:22.
 */
class IconSetTest extends PHPUnit_Framework_TestCase {
    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }
    
    public function testInstantiatingWithEitherArrayOrId() {
        $this->assertInternalType('object', new IconSet(array('test', 'test2', 'test3')), 32);
        $this->assertInternalType('object', new IconSet(3), 32);
    }
    
    public function testInvalidArgumentExceptionWhenStringPassed() {
        $this->setExpectedException('InvalidArgumentException');
        $iconSet = new IconSet('invalid', 32);
    }
    
    public function testGetMarkupReturnsAllRequestedIcons() {
        $iconSet = new IconSet(array('twitter', 'facebook', 'playstation', 'reddit'));
        $this->assertStringMatchesFormat('%Atwitter%A', $iconSet->getMarkup());
        $this->assertStringMatchesFormat('%Afacebook%A', $iconSet->getMarkup());
        $this->assertStringMatchesFormat('%Aplaystation%A', $iconSet->getMarkup());
        $this->assertStringMatchesFormat('%Areddit%A', $iconSet->getMarkup());
    }
    
    public function testGetMarkupDoesNotReturnNotRequestedIcons() {
        $iconSet = new IconSet(array('digg', 'linkedin', 'twitter'));
        $this->assertStringNotMatchesFormat('%Astumbleupon%A', $iconSet->getMarkup());
        $this->assertStringNotMatchesFormat('%Axing%A', $iconSet->getMarkup());
    }
    
    

}

?>
