<?php

require_once dirname(__FILE__) . '/../../../class/MultipleSocialMediaIcons.php';

/**
 * Test class for MultipleSocialMediaIcons.
 * Generated by PHPUnit on 2012-03-31 at 11:18:16.
 */
class MultipleSocialMediaIconsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var MultipleSocialMediaIcons
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new MultipleSocialMediaIcons;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers MultipleSocialMediaIcons::install
     * @todo Implement testInstall().
     */
    public function testInstall() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::install_db
     * @todo Implement testInstall_db().
     */
    public function testInstall_db() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_localization
     * @todo Implement testInit_localization().
     */
    public function testInit_localization() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_scripts
     * @todo Implement testInit_scripts().
     */
    public function testInit_scripts() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_styles
     * @todo Implement testInit_styles().
     */
    public function testInit_styles() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_shortcodes
     * @todo Implement testInit_shortcodes().
     */
    public function testInit_shortcodes() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::plugin_boilerplate_shortcode
     * @todo Implement testPlugin_boilerplate_shortcode().
     */
    public function testPlugin_boilerplate_shortcode() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_custom_post_types
     * @todo Implement testInit_custom_post_types().
     */
    public function testInit_custom_post_types() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::init_admin_menu
     * @todo Implement testInit_admin_menu().
     */
    public function testInit_admin_menu() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::main_menu_page
     * @todo Implement testMain_menu_page().
     */
    public function testMain_menu_page() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers MultipleSocialMediaIcons::sub_menu_page
     * @todo Implement testSub_menu_page().
     */
    public function testSub_menu_page() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}

?>
