<?php

require_once dirname(__FILE__) . '/../../pages/CreateIconSets.php';

/**
 * Test class for CreateIconSets.
 * Generated by PHPUnit on 2012-04-06 at 19:15:48.
 */
class CreateIconSetsTest extends PHPUnit_Framework_TestCase {

    /**
     * @var CreateIconSets
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CreateIconSets;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}

?>
